### ISSUE TITLE
Public Test Issue Application

### ISSUE THREAD

**Issue by zzooppii** [tokamak-network/crossTrade#57]
### Task Name
- [x] Modified so that the attack is impossible because editAmount is missing in provideCT (https://github.com/tokamak-network/tokamak-bridge/issues/188)
- [x] Added a comment that special ERC20 that incurs a fee when transferring is not supported (https://github.com/tokamak-network/tokamak-bridge/issues/190)
- [x] Add initialize to check L1chainId when requestNonRegisteredToken (https://github.com/tokamak-network/tokamak-bridge/issues/199)
- [x] Added comment on require statement for hash value (https://github.com/tokamak-network/tokamak-bridge/issues/206)
- [x] Added a comment about the require statement for the frontend (https://github.com/tokamak-network/tokamak-bridge/issues/208)

### Add Task
- [x] New Deploy & Setting the CrossTradeContract on Sepolia & Titan Sepolia

**Comment by zzooppii** [comment]
Sepolia
L1CrossTradeLogic : 0xA3139764F343f44A7809dA51DC3a34C3d94450d0

Titan Sepolia
L2CrossTradeLogic 0x656Cd3f9fe074a71Cb19707CDEd5e020F71db097
